/**
 * Garibar take-home assignment — mock API
 * Do not edit this file.
 */

const delay = (ms = 300) => new Promise((resolve) => setTimeout(resolve, ms));

let orders = [
  {
    id: 1,
    goods_name: 'Steel coils',
    origin_city: 'Tehran',
    destination_city: 'Isfahan',
    weight_ton: 18,
    price_rial: 85000000,
    status: 'open',
    created_at: '2026-01-10T08:00:00.000Z',
    description: 'Needs covered truck',
  },
  {
    id: 2,
    goods_name: 'Wheat',
    origin_city: 'Mashhad',
    destination_city: 'Tehran',
    weight_ton: 24,
    price_rial: 62000000,
    status: 'open',
    created_at: '2026-01-11T09:15:00.000Z',
  },
  {
    id: 3,
    goods_name: 'Ceramic tiles',
    origin_city: 'Yazd',
    destination_city: 'Shiraz',
    weight_ton: 12,
    price_rial: 48000000,
    status: 'in_progress',
    created_at: '2026-01-12T10:30:00.000Z',
    description: 'Fragile cargo',
  },
  {
    id: 4,
    goods_name: 'Plastic granules',
    origin_city: 'Tehran',
    destination_city: 'Tabriz',
    weight_ton: 20,
    price_rial: 91000000,
    status: 'open',
    created_at: '2026-01-13T11:00:00.000Z',
  },
  {
    id: 5,
    goods_name: 'Cement bags',
    origin_city: 'Ahvaz',
    destination_city: 'Tehran',
    weight_ton: 26,
    price_rial: 105000000,
    status: 'closed',
    created_at: '2026-01-05T07:45:00.000Z',
  },
  {
    id: 6,
    goods_name: 'Apples',
    origin_city: 'Urmia',
    destination_city: 'Tehran',
    weight_ton: 8,
    price_rial: 35000000,
    status: 'open',
    created_at: '2026-01-14T06:20:00.000Z',
    description: 'Refrigerated transport',
  },
  {
    id: 7,
    goods_name: 'Auto parts',
    origin_city: 'Tehran',
    destination_city: 'Mashhad',
    weight_ton: 5,
    price_rial: 28000000,
    status: 'in_progress',
    created_at: '2026-01-15T13:10:00.000Z',
  },
  {
    id: 8,
    goods_name: 'Cotton bales',
    origin_city: 'Kerman',
    destination_city: 'Bandar Abbas',
    weight_ton: 22,
    price_rial: 112000000,
    status: 'open',
    created_at: '2026-01-16T08:50:00.000Z',
  },
  {
    id: 9,
    goods_name: 'Glass panels',
    origin_city: 'Qazvin',
    destination_city: 'Tehran',
    weight_ton: 14,
    price_rial: 67000000,
    status: 'closed',
    created_at: '2026-01-02T15:00:00.000Z',
  },
  {
    id: 10,
    goods_name: 'Fertilizer',
    origin_city: 'Shiraz',
    destination_city: 'Ahvaz',
    weight_ton: 30,
    price_rial: 98000000,
    status: 'open',
    created_at: '2026-01-17T09:40:00.000Z',
  },
  {
    id: 11,
    goods_name: 'Wooden pallets',
    origin_city: 'Rasht',
    destination_city: 'Tehran',
    weight_ton: 10,
    price_rial: 41000000,
    status: 'in_progress',
    created_at: '2026-01-18T12:25:00.000Z',
  },
  {
    id: 12,
    goods_name: 'Copper wire',
    origin_city: 'Zanjan',
    destination_city: 'Isfahan',
    weight_ton: 7,
    price_rial: 55000000,
    status: 'open',
    created_at: '2026-01-19T14:05:00.000Z',
  },
  {
    id: 13,
    goods_name: 'Bottled water',
    origin_city: 'Tehran',
    destination_city: 'Karaj',
    weight_ton: 16,
    price_rial: 32000000,
    status: 'closed',
    created_at: '2026-01-03T10:00:00.000Z',
  },
  {
    id: 14,
    goods_name: 'Solar panels',
    origin_city: 'Tehran',
    destination_city: 'Yazd',
    weight_ton: 9,
    price_rial: 76000000,
    status: 'open',
    created_at: '2026-01-20T11:30:00.000Z',
    description: 'Handle with care',
  },
  {
    id: 15,
    goods_name: 'Rice sacks',
    origin_city: 'Gorgan',
    destination_city: 'Tehran',
    weight_ton: 21,
    price_rial: 59000000,
    status: 'open',
    created_at: '2026-01-21T07:15:00.000Z',
  },
];

let nextId = 16;

const VALID_STATUSES = ['open', 'in_progress', 'closed'];

const normalize = (value) => String(value || '').trim().toLowerCase();

const assertNonEmptyString = (value, field) => {
  if (typeof value !== 'string' || !value.trim()) {
    throw new Error(`${field} is required`);
  }

  return value.trim();
};

const assertPositiveNumber = (value, field) => {
  const number = Number(value);

  if (!Number.isFinite(number) || number <= 0) {
    throw new Error(`${field} must be a positive number`);
  }

  return number;
};

const parseStatus = (value, { defaultStatus } = {}) => {
  if (value === undefined || value === null || value === '') {
    if (defaultStatus) return defaultStatus;
    throw new Error('status is required');
  }

  if (!VALID_STATUSES.includes(value)) {
    throw new Error('status is invalid');
  }

  return value;
};

const parseDescription = (value) => {
  if (value === undefined || value === null || value === '') {
    return undefined;
  }

  if (typeof value !== 'string') {
    throw new Error('description must be a string');
  }

  const trimmed = value.trim();
  return trimmed || undefined;
};

const filterOrders = (params = {}) => {
  let result = [...orders];

  if (params.status) {
    result = result.filter((order) => order.status === params.status);
  }

  if (params.origin_city) {
    const origin = normalize(params.origin_city);
    result = result.filter((order) => normalize(order.origin_city).includes(origin));
  }

  if (params.search) {
    const search = normalize(params.search);
    result = result.filter((order) => normalize(order.goods_name).includes(search));
  }

  return result;
};

export async function getCargoOrders(params = {}) {
  await delay();

  const page = Number(params.page) > 0 ? Number(params.page) : 1;
  const perPage = Number(params.per_page) > 0 ? Number(params.per_page) : 10;

  const filtered = filterOrders(params);
  const total = filtered.length;
  const start = (page - 1) * perPage;
  const data = filtered.slice(start, start + perPage);

  return {
    data,
    total,
    page,
    per_page: perPage,
  };
}

export async function createCargoOrder(payload = {}) {
  await delay();

  const newOrder = {
    id: nextId++,
    goods_name: assertNonEmptyString(payload.goods_name, 'goods_name'),
    origin_city: assertNonEmptyString(payload.origin_city, 'origin_city'),
    destination_city: assertNonEmptyString(payload.destination_city, 'destination_city'),
    weight_ton: assertPositiveNumber(payload.weight_ton, 'weight_ton'),
    price_rial: assertPositiveNumber(payload.price_rial, 'price_rial'),
    status: parseStatus(payload.status, { defaultStatus: 'open' }),
    created_at: new Date().toISOString(),
  };

  const description = parseDescription(payload.description);

  if (description) {
    newOrder.description = description;
  }

  orders = [newOrder, ...orders];

  return { data: newOrder };
}

export async function updateCargoOrder(id, payload = {}) {
  await delay();

  const orderId = Number(id);
  const index = orders.findIndex((order) => order.id === orderId);

  if (index === -1) {
    throw new Error('Cargo order not found');
  }

  const current = orders[index];
  const updates = {};

  if (payload.goods_name !== undefined) {
    updates.goods_name = assertNonEmptyString(payload.goods_name, 'goods_name');
  }

  if (payload.origin_city !== undefined) {
    updates.origin_city = assertNonEmptyString(payload.origin_city, 'origin_city');
  }

  if (payload.destination_city !== undefined) {
    updates.destination_city = assertNonEmptyString(payload.destination_city, 'destination_city');
  }

  if (payload.weight_ton !== undefined) {
    updates.weight_ton = assertPositiveNumber(payload.weight_ton, 'weight_ton');
  }

  if (payload.price_rial !== undefined) {
    updates.price_rial = assertPositiveNumber(payload.price_rial, 'price_rial');
  }

  if (payload.status !== undefined) {
    updates.status = parseStatus(payload.status);
  }

  if (payload.description !== undefined) {
    updates.description = parseDescription(payload.description);
  }

  const updatedOrder = {
    ...current,
    ...updates,
    id: current.id,
    created_at: current.created_at,
  };

  if (!updatedOrder.description) {
    delete updatedOrder.description;
  }

  orders[index] = updatedOrder;

  return { data: updatedOrder };
}

export async function deleteCargoOrder(id) {
  await delay();

  const orderId = Number(id);
  const exists = orders.some((order) => order.id === orderId);

  if (!exists) {
    throw new Error('Cargo order not found');
  }

  orders = orders.filter((order) => order.id !== orderId);

  return { message: 'Cargo order deleted' };
}
